{
    'name': 'Laundry Management',
    'version': '19.0.1.0.0',
    'summary': 'Complete laundry order management with tasks, services, and invoicing',
    'description': 'Manage laundry orders, cloth tracking, washing services, tasks, invoicing, and customer ratings.',
    'author': 'LeapAI',
    'website': 'https://leapai.com',
    'category': 'Services',
    'license': 'LGPL-3',
    'images': [
        'static/description/main_screenshot.png',
        'static/description/screenshot_orders.png',
        'static/description/icon.png',
    ],
    'depends': ['account', 'hr', 'mail', 'product'],
    'data': [
        'security/laundry_security.xml',
        'security/ir.model.access.csv',
        'data/laundry_sequence.xml',
        'data/laundry_data.xml',
        'views/laundry_cloth_size_views.xml',
        'views/laundry_cloth_type_views.xml',
        'views/laundry_service_views.xml',
        'views/laundry_order_views.xml',
        'views/laundry_task_views.xml',
        'views/laundry_rating_views.xml',
        'views/laundry_dashboard_views.xml',
        'views/laundry_menus.xml',
        'wizard/laundry_pickup_wizard_views.xml',
        'report/laundry_order_report.xml',
        'report/laundry_order_report_template.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'leapai_laundry_management/static/src/components/dashboard/dashboard.js',
            'leapai_laundry_management/static/src/components/dashboard/dashboard.xml',
            'leapai_laundry_management/static/src/components/dashboard/dashboard.scss',
        ],
    },
    'demo': ['demo/laundry_demo.xml'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
