{
    'name': 'App API (Firebase)',
    'version': '19.0.1.0.0',
    'category': 'Sales/Sales',
    'summary': 'REST endpoints for a FlutterFlow client app authenticated with Firebase',
    'author': 'QBH',
    'license': 'LGPL-3',
    'depends': ['base', 'account', 'sale_management', 'sales_team',
                'loyalty', 'sale_loyalty'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_config_parameter.xml',
        'views/res_partner_views.xml',
        'views/product_views.xml',
        'views/sale_order_views.xml',
        'views/res_config_settings_views.xml',
        'views/app_dashboard_views.xml',
        'views/wallet_views.xml',
        'wizards/app_wallet_topup_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': True,
}
