{
    'name': 'App API (Firebase)',
    'version': '19.0.1.7.0',
    'category': 'Sales/Sales',
    'summary': 'REST endpoints for a FlutterFlow client app authenticated with Firebase',
    'author': 'QBH',
    'license': 'LGPL-3',
    'depends': ['base', 'account', 'sale_management', 'sales_team',
                'loyalty', 'sale_loyalty', 'point_of_sale', 'pos_restaurant'],
    'data': [
        'security/app_api_security.xml',
        'security/ir.model.access.csv',
        'data/ir_config_parameter.xml',
        'data/app_api_endpoint_data.xml',
        'data/app_section_data.xml',
        'views/app_api_endpoint_views.xml',
        'views/app_section_views.xml',
        'views/res_partner_views.xml',
        'views/product_views.xml',
        'views/pos_category_views.xml',
        'views/restaurant_table_views.xml',
        'views/sale_order_views.xml',
        'views/res_config_settings_views.xml',
        'views/app_dashboard_views.xml',
        'views/wallet_views.xml',
        'wizards/app_wallet_topup_views.xml',
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'odoo_app_api/static/src/scss/app_dashboard.scss',
        ],
    },
    'installable': True,
    'application': True,
}
