from . import staff_allowance_beneficiary_mixin
from . import staff_allowance_rule
from . import staff_allowance_plan
from . import staff_allowance_order
from . import staff_allowance_usage
from . import staff_allowance_attempt
from . import hr_employee
from . import res_partner
from . import pos_order
from . import staff_allowance_give
